accounts/urls.py
from django.conf.urls import include, url

from accounts import views

urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^register/$', views.RegistrationView.as_view(), name='register'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
]

cowork/urls.py
from django.conf.urls import include, url

from cowork import views

urlpatterns = [
    url(r'^dashboard/$', views.DashboardView.as_view(), name='dashboard'),
    url(r'^locations/', include('cowork.locations.urls', namespace='locations')),
    url(r'^search/$', views.SearchView.as_view(), name='search'),
    url(r'^rent/(?P<pk>\d+)$', views.rent_desk, name='rent'),
]

coworkok/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from coworkok import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^cowork/', include('cowork.urls', namespace='cowork')),
    url(r'^admin/', include(admin.site.urls)),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coworkok/views.py
from django.views.generic import TemplateView


class IndexView(TemplateView):
    template_name = 'index.html'

coworkok/templates/base.html
{% load pipeline staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}CoWorkOK{% endblock %}</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

    {% stylesheet 'dashboard' %}
    {% block css %}{% endblock %}

  </head>
  <body>
      {% if request.user.is_authenticated %}
        {% include "navbar/navbar_auth.html" %}
      {% else %}
        {% include "navbar/navbar_not_auth.html" %}
      {% endif %}
      {% block header %}{% endblock %}
      {% block content %}{% endblock %}
      <hr>
      <div class="container">
        <footer>{% block footer %}<p>&copy; Company 2014</p>{% endblock %}</footer>
      </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
    {% block js %}{% endblock %}
  </body>
</html>

coworkok/templates/index.html
{% extends "base.html" %}

{% block content %}
<div class="jumbotron">
  <div class="container">
    
    <div class="row text-center">
      <div class="col-md-6">
  
        <h2 class="index-header"> Would you like to hire desk in your location</h2>    
        <a href="{% url 'accounts:register' %}" class="btn btn-success btn-lg">Sign up!</a>

      </div>
      <div class="col-md-6">
        <h2 class="index-header"> Would you like to rent a desk? </h2>
        <a href="{% url 'cowork:search' %}" class="btn btn-primary btn-lg">Search in your city</a>
      </div>
    </div>

  </div>
</div>

<div class="container">
  <!-- Example row of columns -->
  <div class="row">
    <div class="col-md-4">
      <h2>Heading</h2>
      <p class="lipsum"></p>
      <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
    </div>
    <div class="col-md-4">
      <h2>Heading</h2>
      <p class="lipsum"></p>
      <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
   </div>
    <div class="col-md-4">
      <h2>Heading</h2>
      <p class="lipsum"></p>
      <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
    </div>
  </div>
</div>
{% endblock %}