accounts/urls.py
from django.conf.urls import include, url

from accounts import views

urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^register/$', views.RegistrationView.as_view(), name='register'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
]

cowork/urls.py
from django.conf.urls import include, url

from cowork import views

urlpatterns = [
    url(r'^dashboard/$', views.DashboardView.as_view(), name='dashboard'),
    url(r'^locations/', include('cowork.locations.urls', namespace='locations')),
    url(r'^search/$', views.SearchView.as_view(), name='search'),
    url(r'^rent/(?P<pk>\d+)$', views.rent_desk, name='rent'),
]

coworkok/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from coworkok import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^cowork/', include('cowork.urls', namespace='cowork')),
    url(r'^admin/', include(admin.site.urls)),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coworkok/views.py
from django.views.generic import TemplateView


class IndexView(TemplateView):
    template_name = 'index.html'

coworkok/templates/navbar/navbar_auth.html
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'cowork:dashboard' %}">CoWorkOK</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'cowork:dashboard' %}">Dashboard</a></li>
        <li><a href="#">Settings</a></li>
        <li><a href="#">{{user}}</a></li>
        <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
      </ul>
      <form class="navbar-form navbar-right">
        <input type="text" class="form-control" placeholder="Search...">
      </form>
    </div>
  </div>
</nav>

coworkok/templates/navbar/navbar_not_auth.html
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'index' %}">CoWorkOK</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <form method="post" action="{% url 'accounts:login' %}" class="navbar-form navbar-right ">
        {% csrf_token %}
        <div class="form-group">
          <input class="form-control" id="id_username" name="username" placeholder="Email" type="email">
        </div>
        <div class="form-group">
          <input class="form-control" id="id_password" name="password" placeholder="Password" type="password">
        </div>
        <button type="submit" class="btn btn-success">Sign in</button>
        <a href="/accounts/register" class="btn btn-info" role="button">Register</a>
      </form>

    </div><!--/.navbar-collapse -->


    </div>
  </div>
</nav>